export default
    {
        base_url: 'https://starlinkinfluencers.in/api/v1', // Live server url
         //base_url:'https://dev.starlinkinfluencers.in/api/v1', // Dev server url    // https://starlinkinfluencers.in/api/v1/get-order-by-mason
         // Dev server url    // https://starlinkinfluencers.in/api/v1/get-order-by-mason


        login: 'auth/login',
        logout: 'auth/logout',
        language_change: 'update-user-preferences',
        register: 'auth/register',
        send_otp: 'auth/send-otp',
        my_profile: 'user-profile',
        get_branches: 'get-branchies',
        get_dealer_rssd: 'get-branch-dealer-rssd',
        send_otp_to_new_number: 'auth/send-otp-to-new-number',
        verify_phone: 'verify-phone',
        mason_register: 'te/mason-register',
        update_profile: 'update-profile',
        change_profile_pic: 'change-profile-pic',
        aadhaar_image_upload: 'te/update-mason/',
        get_all_products: 'get-all-products',
        add_lifting: 'add-lifting',
        check_duplicate_lifting:'check-duplicate-lifting',
        get_my_mason: 'get-my-masons',
        get_lifting_history: 'get-lifting-history',
        get_all_dealer_ssd: 'get-all-dealer-rssd',
        get_dealers_by_mason: 'get-dealers-by-mason',
        send_query: 'send-query',
        update_lifting: 'update-lifting',
        get_rewards: 'get-rewards',
        get_about_us: 'get-about-us',
        privacy_policy: 'privacy-policy',
        //terms_and_conditions: 'terms-and-conditions',
        get_faq: 'get-faq',
        get_contact: 'get-contact',
        get_social_link: 'get-social-link',
        get_gift_catalog: 'get-gift-catalog',
        get_gift_catalogues:'get-gift-catalogues',
        get_gifts_by_catalogue:'get-gifts-by-catalogue/',
        get_redeemtion: 'get-redeemtion',
        get_notification: 'get-notification',
        apply_redeemtion: 'apply-redeemtion',
        get_rewards_by_mason: 'get-rewards-by-mason',
        get_redeemtion_by_mason: 'get-redeemtion-by-mason',
        get_all_dealers: 'get-all-dealers',
        view_banner: 'view-banner',
        getOrder: 'get-order-by-mason',
        confirmOrder: 'confirm-gift-delivery/',
        getSupport: 'get-support',
        saveSupport: 'save-support',
        delete_user: 'auth/account-delete',
        app_registration_link_visible: 'settings',
        test_branch: 'test/branch',
        test_dealer: 'test/dealers',
        test_te: 'test/te',
        test_register_mason: 'test/register-mason',
        test_all_branch: 'test/all-branch',
        test_register_te: 'test/register-te',
        app_version:'get-app-versions',

        UPDATE_USER: 'UPDATE_USER',
        RESET_USER: 'RESET_USER',

        te_dashboard: 'te/dashboard',
        accept_lifting:'te/starsaathi/accept-lifting',
        reject_lifting:'te/starsaathi/reject-lifting',
        te_edit_lifting:'te/starsaathi/accept-lifting',
        te_mason_list:'te/starsaathi/get-te-mason-options',
        linking_dealer:'get-dealers-by-mason-branch',
        link_dealer:'dealer-linking-request',
        accept_linking:'te/accept/dealer-linking_requests',
        reject_linking:'te/reject/dealer-linking_requests',
        flash_banner:'get-flash-banner',
        terms_and_conditions: '/settings',
        submit_order_feedback: '/submit-order-feedback',
        check_user_last_order_acknowledgement: '/check-user-last-order-acknowledgement',
        last_order_details: 'last-order-contact-details',
        store_birthday: '/store-birthday',
        check_and_log_birthday: 'check-and-log-birthday',
        get_birthday: 'get-birthday/',
        delete_account_btn: '/delete_account_btn'


    }