import { useEffect, useState } from 'react'
import DataStore from './DataStore'
const useTextValue = () => {
  const [textValue, setTextValue] = useState(getTextValue(DataStore.language))

  useEffect(() => {
    setTextValue(getTextValue(DataStore.language))
  }, [DataStore.language])
  return textValue
}

const getTextValue = (language) => {
  switch (language) {
    case 'Hindi':
      return {
        Search_by_mobile_number:'मोबाइल नंबर से खोजें',
        Contractor_Profile:'ठेकेदार प्रोफाइल',
        Email:'ई-मेल',
        Updated_Profile:'अद्यतन प्रोफ़ाइल',
        Updated:'अद्यतन',
        Action_Need:'कार्रवाई की आवश्यकता',  
        Contractor_List:'ठेकेदार सूची',
        sorry:'क्षमा मांगना',
        Date_of_Lifting:'उठाने की तिथि',
        Linked_Dealer:'लिंक्ड डीलर',
        ADD_ENQUIRY:'पूछताछ जोड़ें',
        transaction_id:'लेनदेन आईडी',
        Sign_Up_To_Your_Mason:'अपने ठेकेदार के\nलिए साइन अप करें',
        For_All_Your_Cement_Purchases:'आपकी सभी सीमेंट खरीदों के लिए',
        Check_Balance_Points:'बैलेंस पॉइंट जांचें',
        Follow_Us:'हमारे पर का पालन करें',
        otp_message_1:'कृपया वह कोड दर्ज करें जो हम ',
        otp_message_2:' फ़ोन नंबर पर भेजते हैं',
        Verify_Code:'कोड सत्यापित करें',
        HOME: 'लैंडिंग पृष्ठ',
        Home: 'लैंडिंग पृष्ठ',
        Delete: 'मिटाना',
        YES: 'हाँ',
        PROFILE: 'प्रोफ़ाइल',
        Profile: 'प्रोफ़ाइल',
        ORDER_LIST: 'आदेश सूची',
        Order_List: 'आदेश सूची',
        ABOUT_US: 'हमारे बारे में',
        About_Us: 'हमारे बारे में',
        CONTACT_US: 'हमसे संपर्क करें',
        Contact_Us: 'हमसे संपर्क करें',
        TERMS_CONDITIONS: 'नियम और शर्तें',
        Terms_Conditions: 'नियम और शर्तें',
        PRIVACY_POLICY: 'गोपनीयता नीति',
        Privacy_Policy: 'गोपनीयता नीति',
        Logout: 'लॉग आउट',
        Version: 'संस्करण',
        Delete_Account: 'खाता हटा दो',
        MASON_REGISTRATION: 'ठेकेदार\nपंजीकरण',
        LIFTING_HISTORY1: 'उठाने का\nइतिहास',
        LIFTING_HISTORY: 'उठाने का इतिहास',
        REWARD_POINTS: 'ईनामी\nअंक',
        DASHBOARD1: 'डैशबोर्ड',
        DASHBOARD: 'डैशबोर्ड',
        ADD_LIFTING: 'लिफ्टिंग जोड़ें',
        ADD_LIFTING1: 'लिफ्टिंग\nजोड़ें',
        GIFT_CATALOGUE1: 'उपहार\nसूची',
        GIFT_CATALOGUE: 'उपहार सूची',
        REQUEST_A_DEALER1: 'एक डीलर से\nअनुरोध करें',
        REQUEST_A_DEALER: 'एक डीलर से अनुरोध करें',
        MASON_SALES_ENTRY1: 'ठेकेदार बिक्री\nप्रविष्टि',
        MASON_SALES_ENTRY: 'ठेकेदार बिक्री प्रविष्टि',
        LIFTING_APPROVAL1: 'अनुमोदन\nउठाना',
        LIFTING_APPROVAL: 'अनुमोदन उठाना',
        DEALER_LINK_REQUEST: 'डीलर लिंक अनुरोध',
        DEALER_LINK_REQUEST1: 'डीलर लिंक\nअनुरोध',
        ORDER_ENQUIRY:'ऑर्डर पूछताछ',
        ORDER_ENQUIRY1:'ऑर्डर\nपूछताछ',
        NEW_ORDER_ENQUIRY:'नया ऑर्डर पूछताछ',
        Cancel: 'रद्द करना',
        Edit_Profile: 'प्रोफ़ाइल संपादित करें',
        Save: 'बचाना',
        Your_Name: 'आपका नाम',
        Your_Phone_no: 'आपका फ़ोन नं',
        Your_Mail: 'आपकी मेल',
        Technical_Engineer_Name: 'बीडीई का नाम',
        Technical_Engineer_Mobile: 'बीडीई मोबाइल',
        Aadhaar_no: 'आधार नं',
        Categoty: 'वर्ग',
        Address_1: 'पता 1',
        Address_2: 'पता 2',
        City: 'शहर',
        District: 'ज़िला',
        State: 'राज्य',
        Country: 'देश',
        Pin: 'ज़िप कोड',
        Employee_Id: 'कर्मचारी आयडी',
        Employee_Id1: 'कर्मचारी आयडी',
        Aadhaar__documant:'आधार दस्तावेज़',
        Dealer_Code: 'डीलर कोड',
        Rssd_Code: 'आरएसएसडी कोड',
        Enter_your_Mobile_number: 'अपना मोबाइल संख्या दर्ज करे',
        Enter_mobile_number: 'मोबाइल नंबर दर्ज करें',
        Next: 'अगला',
        Dont_have_an_account_yet: 'अब तक कोई खाता नहीं है?',
        for_Mason: 'ठेकेदार के लिए',
        Or: 'या',
        for_Technical_Engineer: 'बीडीई के लिए',
        Verification_code: 'सत्यापन कोड',
        Enter_code: 'कोड दर्ज करें',
        Please_enter_verification_code: 'कृपया सत्यापन कोड दर्ज करें',
        Send_to_your_mobile_no: 'अपने मोबाइल नंबर पर भेजें',
        Didnt_receive_an_OTP: 'ओ.टी.पी नहीं मिला?',
        Resend_OTP: 'ओ.टी.पी दोबारा भेजें?',
        Verify: 'सत्यापित करें',
        MASON: 'ठेकेदार',
        REGISTRATION: 'पंजीकरण',
        Full_name_of_mason: 'पूरा नाम',
        Enter_Mobile_Number: 'मोबाइल नंबर दर्ज करें',
        Enter_Email_Id:'ईमेल आईडी दर्ज करें',
        Search: 'खोज',
        Marital_Status: 'वैवाहिक स्थिति',
        Select_branch: 'शाखा का चयन करें',
        Select_Technical_Engineer: 'बीडीई का चयन करें',
        DATE_OF_BIRTH: 'जन्म तिथि',
        Enter_Aadhar_number: 'आधार नंबर दर्ज करें',
        Enter_Voter_number: 'मतदाता क्रमांक दर्ज करें',
        Choose_File: 'फाइलें चुनें',
        Upload_Aadhaar: 'आधार अपलोड करें',
        Upload_Voter: 'मतदाता अपलोड करें',
        Register: 'पंजीकरण करवाना',
        TECHNICAL_ENGINEER: 'बीडीई',
        Full_name: 'पूरा नाम',
        Employee_Code: 'कर्मचारी कोड',
        Phone: 'फ़ोन',
        Your_number_is_verified: 'आपका नंबर सत्यापित है',
        Language_change_successfully:'भाषा परिवर्तन सफलतापूर्वक',
        Successfully_language_changed: 'सफलतापूर्वक भाषा बदल गई',
        Login: 'लॉग इन करें',
        SUPPORT: 'सहायता',
        Get_In_Touch: 'संपर्क में रहो',
        Message: 'संदेश',
        Submit: 'जमा करना',
        Submit1: 'जमा करना',
        SUPPORT_LIST: 'समर्थन सूची',
        Name: 'नाम',
        Comment: 'टिप्पणी',
        Status: 'स्थिति',
        Pending: 'लंबित',
        Resolved: 'हल किया',
        Rejected: 'अस्वीकार कर दिया',
        No_Data_Found: 'डाटा प्राप्त नहीं हुआ',
        Gift_not_available: 'कृपया पुरस्कार के लिए अगले स्लैब के लिए अर्हता प्राप्त करें',
        REJECT: 'अस्वीकार करना',
        ACCEPT: 'स्वीकार करना',
        Approved: 'अनुमत',
        Are_you_want_to_accept_the_lifting: 'क्या आप लिफ्ट स्वीकार\nकरना चाहते हैं?',
        Select_your_reason: 'अपना कारण चुनें',
        DATE: 'तारीख',
        DESCRIPTION: 'विवरण',
        POINTS: 'अंक',
        EARNED: 'अर्जित',
        REDEEMED: 'छुड़ाया',
        REWARD_DETAILS: 'पुरस्कार विवरण',
        NET_POINTS: 'शुद्ध अंक',
        AVAILABLE_POINTS : 'उपलब्ध अंक',
        Month: 'महीना',
        Year: 'वर्ष',
        Select_Mason: 'ठेकेदार का चयन करें',
        Redeem_Now: 'अब एवज करें',
        LINK: 'जोड़ना',
        Registration: 'पंजीकरण',
        Successful: 'सफल',
        Order_Id: 'आदेश कामतत्व',
        Date: 'तारीख',
        Description: 'विवरण',
        Points: 'अंक',
        Delivery_Status: 'डिलीवरी स्टेटस',
        Delivered: 'पहुंचा दिया',
        Delivery_Date: 'डिलीवरी की तारीख',
        Support: 'सहायता',
        View_Support: 'समर्थन देखें',
        NOTIFICATION: 'अधिसूचना',
        Enter_Code: 'कोड दर्ज करें',
        Please_Enter_Verification_Code: 'कृपया सत्यापन कोड दर्ज करें',
        Send_To_Your_Mobile: 'अपने मोबाइल पर भेजें',
        Spouse_name: 'जीवनसाथी का नाम',
        Spouse_DoB: 'पति के जन्म की तारीख',
        SPOUSES_DATE_OF_BIRTH: 'पति के जन्म की तारीख',
        EDIT: 'संपादन करना',
        From_Date: 'की तिथि से',
        To_Date: 'तारीख तक',
        Are_you_want_to_accept_the_lifting: 'क्या आप उठाव\nस्वीकार करना चाहते हैं?',
        Edit_Pending_Lifting: 'लंबित उठान संपादित करें',
        Product: 'उत्पाद',
        Lifting_Date: 'उठाने की तिथि',
        Mason_Name: 'ठेकेदार नाम',
        Mason_Phone: 'ठेकेदार फ़ोन',
        No_of_Bags: 'बैग की संख्या',
        Accept: 'स्वीकार करना',
        PRODUCTS: 'उत्पादों',
        NO_OF_BAGS: 'बैग की संख्या',
        LIFTING_DATE: 'उठाने की तिथि',
        POINTS: 'अंक',
        In_progress: 'प्रगति पर है',
        DEALER: 'डीलर',
        RSSD: 'आरएसएसडी',
        SUB_DEALER: 'उप-डीलर',
        STAR_SAATHI_STATUS: 'स्टार साथी स्थिति',
        APPROVED_REJECTED_DATE_AND_TIME: 'स्वीकृत/अस्वीकृत दिनांक और समय',
        Search_Name: 'नाम खोजें',
        Mobile_No: 'मोबाइल नहीं है',
        Aadhar: 'आधार',
        UPDATE_LIFTING_DETAILS: 'उठाने का विवरण अद्यतन करें',
        Select_Product: 'उत्पाद का चयन करें',
        Enter_Qty_No_Of_Bags: 'मात्रा दर्ज करें (बैग की संख्या)',
        Remarks: 'टिप्पणी',
        CANCEL: 'रद्द करना',
        UPDATE: 'अद्यतन',
        GIFT_REDEMPTION: 'उपहार मोचन',
        Address: 'पता',
        t0: 'iOS इनपुट सुझाव के लिए रिएक्ट नेटिव 0.58+ की आवश्यकता होती है और यह iOS 12 और इसके बाद के संस्करण के लिए काम करता है। iOS इनपुट सुझाव के लिए रिएक्ट नेटिव 0.58+ की आवश्यकता होती है और यह iOS 12 और इसके बाद के संस्करण के लिए काम करता है।',
        Total_Bags: 'कुल बैग',
        Are_you_sure_to_redeemed_this_product: 'क्या आप निश्चित रूप से इस उत्पाद को भुना लेंगे?',
        Redeem: 'भुनाना',
        FAQ: 'अक्सर पूछे जाने वाले प्रश्नों',
        Total_Linked_Mason: 'कुल लिंक्ड ठेकेदार',
        Active_Mason: 'सक्रिय ठेकेदार',
        Verified_Lifting: 'सत्यापित लिफ्टिंग',
        Unverified_Lifting: 'असत्यापित भारोत्तोलन',
        Total_Ppc_Lifting_Bag: 'कुल पीपीसी लिफ्टिंग बैग',
        Total_Arc_Lifting_Bag: 'टोटल आर्क लिफ्टिंग बैग',
        Mason_Net_Point: 'ठेकेदार नेट प्वाइंट',
        Gift_Redeemed: 'उपहार भुनाया गया',
        Gift_pending: 'उपहार लंबित है',
        Gift_Delivered: 'उपहार वितरित किया गया',
        Gift_Rejected:'उपहार अस्वीकृत',
        Gift_Order_Placed:'उपहार ऑर्डर दिया गया',
        Query_Raised: 'प्रश्न उठाया',
        Query_pending: 'क्वेरी लंबित है',
        Query_resolved: 'क्वेरी का समाधान हो गया',
        Dealer: 'विक्रेता',
        Mason_mobile: 'ठेकेदार मोबाइल',
        Mason_branch: 'ठेकेदार शाखा',
        Te_Code: 'बीडीई कोड',
        Te_Name: 'बीडीई नाम',
        Te_Phone: 'बीडीई फोन',
        Zone: 'जोन',
        Product_name: 'प्रोडक्ट का नाम',
        Product_quantity: 'उत्पाद गुणवत्ता',
        Verified_by: 'द्वारा सत्यापित',
        Adhaar: 'आधार',
        DOB: 'जन्म तिथि',
        Marrital_Status: 'वैवाहिक स्थिति',
        Spouce_Name: 'जीवनसाथी का नाम',
        Spouce_DOB: 'जीवनसाथी की जन्मतिथि',
        Branch_Name: 'शाखा का नाम',
        Zone_Name: 'जोन का नाम',
        Created_By: 'के द्वारा बनाई गई',
        Linked_TE_Name: 'लिंक किया गया बीडीई नाम',
        Mason_category: 'ठेकेदार श्रेणी',
        Order_no: 'आदेश संख्या',
        Employee_name: 'कर्मचारी का नाम',
        Catalogue: 'सूची',
        Type: 'प्रकार',
        Updated_at: 'पर अद्यतन किया गया',
        DASHBOARD_DETAILS: 'डैशबोर्ड विवरण',
        PHONE_NO: 'फोन नंबर।',
        Select_Dealer_Rssd_Sub_Dealer: 'डीलर/आरएसएसडी/उप-डीलर का चयन करें',
        Select_Dealer: 'डीलर का चयन करें',
        ENTER_OTP: 'ओ.टी.पी दर्ज करें',
        Verify_from_OTP: 'ओ.टी.पी से सत्यापित करें',
        Verify_from_Star_Saathi: 'स्टार मेट से सत्यापित करें',
        DELIVERY_ADDRESS: 'डिलिवरी का पता',
        Change_delivery_address: 'डिलीवरी पता बदलें',
        Confirm: 'पुष्टि करना',
        Select_options: 'विकल्प चुनें',
        Camera: 'कैमरा',
        Library: 'फ़ाइल',
        Close: 'बंद करना',
        No_Internet_connection: 'कोई इंटरनेट कनेक्शन नहीं',
        Select_Language: 'भाषा चुने',
        start_date:'आरंभ तिथि',
        end_date:'अंतिम तिथि',
        Phone_no_is_required:'फ़ोन नंबर आवश्यक है',
        Verified:'सत्यापित',
        Send_OTP:'ओ.टी.पी भेजें',
        Select_Language:'भाषा चुने',
        Loading:'लोड हो रहा है'
      }
    case 'Assamese':
      return {
        Search_by_mobile_number:'মোবাইল নম্বৰৰ দ্বাৰা সন্ধান কৰক',
        Contractor_Profile:'ঠিকাদাৰৰ প্ৰফাইল',
        Email:'ই-মেইল',
        Updated_Profile:'আপডেইট কৰা হৈছে আলেখ্যন',
        Updated:'আপডেট কৰা হৈছে',
        Action_Need:'কাৰ্য্যৰ প্ৰয়োজন',  
        Contractor_List:'ঠিকাদাৰৰ তালিকা',
        sorry:'দুঃখিত',
        Date_of_Lifting:'উত্তোলনৰ তাৰিখ',
        Linked_Dealer:'লিংকড ডিলাৰ',
        ADD_ENQUIRY:'অনুসন্ধান যোগ কৰক',
        transaction_id:'লেনদেন আইডি',
        Sign_Up_To_Your_Mason:'আপোনাৰ ঠিকাদাৰ\nচাইন আপ কৰক',
        For_All_Your_Cement_Purchases:'আপোনাৰ সকলো চিমেণ্ট ক্ৰয়ৰ বাবে',
        Check_Balance_Points:'বেলেন্স পইণ্ট পৰীক্ষা কৰক',
        Follow_Us:'আমাক অনুসৰণ কৰক',
        otp_message_1:'অনুগ্ৰহ কৰি আমি ',
        otp_message_2:" ফোন নম্বৰত পঠোৱা ক'ডটো দিব",
        Verify_Code:"ভেৰিফাই ক'ড",
        HOME: 'লেণ্ডিং পেজ',
        Home: 'লেণ্ডিং পেজ',
        Delete: 'বিলোপ',
        YES: 'হয়',
        PROFILE: 'ৰূপৰেখা',
        Profile: 'ৰূপৰেখা',
        ORDER_LIST: 'অৰ্ডাৰ তালিকা',
        Order_List: 'অৰ্ডাৰ তালিকা',
        ABOUT_US: 'আমাৰ বিষয়ে',
        About_Us: 'আমাৰ বিষয়ে',
        CONTACT_US: 'আমাৰ সৈতে যোগাযোগ কৰক',
        Contact_Us: 'আমাৰ সৈতে যোগাযোগ কৰক',
        TERMS_CONDITIONS: 'চৰ্ত আৰু নিয়ম',
        Terms_Conditions: 'চৰ্ত আৰু নিয়ম',
        PRIVACY_POLICY: 'গোপনীয়তা নীতি',
        Privacy_Policy: 'গোপনীয়তা নীতি',
        Logout: 'লগআউট কৰক',
        Version: 'সংস্কৰণ',
        Delete_Account: 'একাউণ্ট মচি পেলাওক',
        MASON_REGISTRATION: 'ঠিকাদাৰ\nপঞ্জীয়ন',
        LIFTING_HISTORY1: 'ইতিহাস\nউত্তোলন কৰা',
        LIFTING_HISTORY: 'ইতিহাস উত্তোলন কৰা',
        REWARD_POINTS: 'পুৰস্কাৰ\nপইণ্ট',
        DASHBOARD1: "ডেচব'ৰ্ড",
        DASHBOARD: "ডেচব'ৰ্ড",
        ADD_LIFTING: 'লিফ্টিং যোগ কৰক',
        ADD_LIFTING1: 'লিফ্টিং\nযোগ কৰক',
        GIFT_CATALOGUE1: 'উপহাৰৰ\nতালিকা',
        GIFT_CATALOGUE: 'উপহাৰৰ তালিকা',
        REQUEST_A_DEALER: 'এজন ডিলাৰক অনুৰোধ কৰক',
        REQUEST_A_DEALER1: 'এজন ডিলাৰক\nঅনুৰোধ কৰক',
        MASON_SALES_ENTRY1: 'ঠিকাদাৰ বিক্ৰী\nপ্ৰৱেশ',
        MASON_SALES_ENTRY: 'ঠিকাদাৰ বিক্ৰী প্ৰৱেশ',
        LIFTING_APPROVAL1: 'উত্তোলনৰ\nঅকাৰ্য্যকৰীতা',
        LIFTING_APPROVAL: 'উত্তোলনৰ অকাৰ্য্যকৰীতা',
        DEALER_LINK_REQUEST1: 'ডিলাৰ লিংক\nঅনুৰোধ',
        DEALER_LINK_REQUEST: 'ডিলাৰ লিংক অনুৰোধ',
        ORDER_ENQUIRY:'অৰ্ডাৰ ইনকিউৰি',
        ORDER_ENQUIRY1:'অৰ্ডাৰ\nইনকিউৰি',
        NEW_ORDER_ENQUIRY:'নতুন অৰ্ডাৰৰ অনুসন্ধান',
        Cancel: 'বাতিল কৰক',
        Edit_Profile: 'প্ৰফাইল সম্পাদনা কৰক',
        Save: 'সঞ্চয় কৰা',
        Your_Name: 'তোমাৰ নাম',
        Your_Phone_no: 'আপোনাৰ ফোন নম্বৰ',
        Your_Mail: 'আপোনাৰ মেইল',
        Technical_Engineer_Name: 'বিডিই নাম',
        Technical_Engineer_Mobile: 'বিডিই মোবাইল',
        Aadhaar_no: 'আধাৰ নং',
        Categoty: 'শ্ৰেণী',
        Address_1: 'ঠিকনা ১',
        Address_2: 'ঠিকনা ২',
        City: 'চহৰ',
        District: 'জিলা',
        State: 'ৰাজ্য',
        Country: 'দেশ',
        Pin: 'জিপ কোড',
        Employee_Id: 'কৰ্মচাৰীৰ আইডি',
        Employee_Id1: 'কৰ্মচাৰীৰ আইডি',
        Aadhaar__documant:'আধাৰ নথি',
        Dealer_Code: "ডিলাৰ ক'ড",
        Rssd_Code: 'আৰএছএছঘ কোড',
        Enter_your_Mobile_number: 'আপোনাৰ মোবাইল নম্বৰ দিয়ক',
        Enter_mobile_number: 'মোবাইল নম্বৰ দিয়ক',
        Next: 'পৰৱৰ্তী',
        Dont_have_an_account_yet: 'এতিয়াও একাউণ্ট নাই নেকি?',
        for_Mason: 'ঠিকাদাৰ বাবে',
        Or: 'অথবা',
        for_Technical_Engineer: 'বিডিই বাবে',
        Verification_code: "সত্যাপন ক'ড",
        Enter_code: "ক'ড দিয়ক",
        Please_enter_verification_code: "অনুগ্ৰহ কৰি সত্যাপন ক'ড দিয়ক",
        Send_to_your_mobile_no: 'আপোনাৰ মোবাইল নং ত পঠাওক',
        Didnt_receive_an_OTP: 'অ’টিপি পোৱা নাছিল নেকি?',
        Resend_OTP: 'অ’টিপি পুনৰ প্ৰেৰণ কৰক?',
        Verify: 'সত্যাপন কৰা',
        MASON: 'ঠিকাদাৰ',
        REGISTRATION: 'পঞ্জীয়ন',
        Full_name_of_mason: 'সম্পূৰ্ণ নাম',
        Enter_Mobile_Number: 'মোবাইল নম্বৰ দিয়ক',
        Enter_Email_Id:'ই-মেইল আইডি দিয়ক',
        Search: 'সন্ধান',
        Marital_Status: 'বৈবাহিক অৱস্থা',
        Select_branch: 'শাখা নিৰ্বাচন কৰক',
        Select_Technical_Engineer: 'বিডিই নিৰ্বাচন কৰক',
        DATE_OF_BIRTH: 'জন্ম তাৰিখ',
        Enter_Aadhar_number: 'আধাৰ নম্বৰ লিখক',
        Enter_Voter_number:'ভোটাৰৰ নম্বৰ লিখক',
        Choose_File: 'ফাইল নিৰ্ব্বাচন কৰক',
        Upload_Aadhaar: 'আধাৰ আপলোড কৰক',
        Upload_Voter: 'ভোটাৰৰ আপলোড কৰক',
        Register: 'পঞ্জীয়ন কৰা',
        TECHNICAL_ENGINEER: 'বিডিই',
        Full_name: 'সম্পূৰ্ণ নাম',
        Employee_Code: 'কৰ্মচাৰীৰ সংহিতা',
        Phone: 'ফোন',
        Your_number_is_verified: 'আপোনাৰ নম্বৰটো পৰীক্ষা কৰা হৈছে',
        Language_change_successfully:'ভাষা পৰিৱৰ্তন সফলতাৰে',
        Successfully_language_changed: 'সফলতাৰে ভাষা সলনি হ’ল',
        Login: 'লগইন কৰক',
        SUPPORT: 'সমৰ্থন',
        Get_In_Touch: 'স্পৰ্শ কৰক',
        Message: 'বাৰ্তা',
        Submit: 'দাখিল কৰক',
        Submit1: 'দাখিল কৰক',
        SUPPORT_LIST: 'সমৰ্থন তালিকা',
        Name: 'নাম',
        Comment: 'মন্তব্য',
        Status: 'স্থিতি',
        Pending: 'বাকী থকা',
        Resolved: 'সমাধান কৰা হৈছে',
        Rejected: 'নাকচ কৰা হৈছে',
        No_Data_Found: "কোনো তথ্য পোৱা নগ'ল",
        Gift_not_available: 'পুৰস্কাৰৰ বাবে পৰৱৰ্তী স্লেবলৈ যোগ্যতা অৰ্জন কৰক',
        REJECT: 'প্ৰত্যাখ্যান',
        ACCEPT: 'গ্ৰহণ কৰা',
        Approved: 'অনুমোদিত',
        Are_you_want_to_accept_the_lifting: 'লিফ্টখন গ্ৰহণ কৰিব\nবিচাৰে নেকি?',
        Select_your_reason: 'আপোনাৰ কাৰণ বাছক',
        DATE: 'তাৰিখ',
        DESCRIPTION: 'বিৱৰণ',
        POINTS: 'পয়েন্ট',
        EARNED: 'অর্জিত',
        REDEEMED: 'মুক্ত কৰা হৈছে',
        REWARD_DETAILS: 'পুৰস্কাৰৰ বিৱৰণ',
        NET_POINTS: 'নেট পইণ্ট',
        AVAILABLE_POINTS: 'উপলব্ধ পইণ্ট',
        Month: 'মাহ',
        Year: 'বছৰ',
        Select_Mason: 'ঠিকাদাৰ নিৰ্বাচন কৰক',
        Redeem_Now: 'এতিয়াই ৰিডিম কৰক',
        LINK: 'লিংক',
        Registration: 'পঞ্জীয়ন',
        Successful: 'সফল',
        Order_Id: 'অৰ্ডাৰ আইডি',
        Date: 'তাৰিখ',
        Description: 'বিৱৰণ',
        Points: 'পইণ্ট',
        Delivery_Status: 'ডেলিভাৰীৰ অৱস্থা',
        Delivered: 'বিলি কৰা হ’ল',
        Delivery_Date: 'ডেলিভাৰীৰ তাৰিখ',
        Support: 'সমৰ্থন',
        View_Support: 'সমৰ্থন চাওক',
        NOTIFICATION: 'জাননী',
        Enter_Code: "ক'ড দিয়ক",
        Please_Enter_Verification_Code: "অনুগ্ৰহ কৰি ভেৰিফিকেচন ক'ড দিয়ক",
        Send_To_Your_Mobile: 'আপোনাৰ মোবাইললৈ পঠাওক',
        Spouse_name: 'পত্নীৰ নাম',
        Spouse_DoB: 'পত্নীৰ জন্ম তাৰিখ',
        SPOUSES_DATE_OF_BIRTH: 'পত্নীৰ জন্ম তাৰিখ',
        EDIT: 'সম্পাদনা কৰক',
        From_Date: 'তাৰিখৰ পৰা',
        To_Date: 'আজিলৈকে',
        Are_you_want_to_accept_the_lifting: 'লিফটিংটো গ্ৰহণ\nকৰিব বিচাৰিছে নেকি?',
        Edit_Pending_Lifting: 'সম্পাদনা বাকী থকা উত্তোলন',
        Product: 'সামগ্ৰী',
        Lifting_Date: 'উত্তোলনৰ তাৰিখ',
        Mason_Name: 'ঠিকাদাৰ নাম',
        Mason_Phone: 'ঠিকাদাৰ ফোন',
        No_of_Bags: 'বেগসমূহৰ সংখ্যা',
        Accept: 'গ্ৰহণ কৰা',
        PRODUCTS: 'সামগ্ৰী',
        NO_OF_BAGS: 'বেগসমূহৰ সংখ্যা',
        LIFTING_DATE: 'উত্তোলনৰ তাৰিখ',
        POINTS: 'পইণ্ট',
        In_progress: 'প্ৰগতিশীল',
        DEALER: 'ডিলাৰ',
        RSSD: 'ৰছীৰে বন্ধা',
        SUB_DEALER: 'সাব-ডিলাৰ',
        STAR_SAATHI_STATUS: 'তাৰকা অংশীদাৰৰ অৱস্থা',
        APPROVED_REJECTED_DATE_AND_TIME: 'অনুমোদিত/প্ৰত্যাখ্যান কৰা তাৰিখ আৰু সময়',
        Search_Name: 'সন্ধানৰ নাম',
        Mobile_No: 'মোবাইল নম্বৰ',
        Aadhar: 'আধাৰ',
        UPDATE_LIFTING_DETAILS: 'উত্তোলনৰ বিৱৰণ আপডেট কৰক',
        Select_Product: 'পণ্য নিৰ্ব্বাচন কৰক',
        Enter_Qty_No_Of_Bags: 'পৰিমাণ (বেগৰ সংখ্যা) লিখক',
        Remarks: 'মন্তব্য',
        CANCEL: 'বাতিল কৰক',
        UPDATE: 'নবীকৰণ',
        GIFT_REDEMPTION: 'উপহাৰ মুক্তি',
        Address: 'ঠিকনা',
        t0: 'iOS ইনপুট পৰামৰ্শৰ বাবে React Native 0.58+ ৰ প্ৰয়োজন আৰু ই iOS 12 আৰু তাৰ ওপৰৰ বাবে কাম কৰে। iOS ইনপুট পৰামৰ্শৰ বাবে React Native 0.58+ ৰ প্ৰয়োজন আৰু ই iOS 12 আৰু তাৰ ওপৰৰ বাবে কাম কৰে।',
        Total_Bags: 'মুঠ বেগ',
        Are_you_sure_to_redeemed_this_product: 'এই প্ৰডাক্টটো আপুনি নিশ্চিতভাৱে ৰিডিম কৰিছেনে?',
        Redeem: 'ৰিডীম কৰা',
        FAQ: 'সঘনাই সোধা প্ৰশ্ন',
        Total_Linked_Mason: 'মুঠ সংযুক্ত ঠিকাদাৰ',
        Active_Mason: 'সক্ৰিয় ঠিকাদাৰ',
        Verified_Lifting: 'পৰীক্ষা কৰা প্ৰত্যাহাৰ',
        Unverified_Lifting: 'পৰীক্ষা নকৰা ওজন উত্তোলন',
        Total_Ppc_Lifting_Bag: 'মুঠ পিপিচি উত্তোলন বেগ',
        Total_Arc_Lifting_Bag: 'মুঠ আৰ্ক লিফটিং বেগ',
        Mason_Net_Point: 'ঠিকাদাৰ নেট পইণ্ট',
        Gift_Redeemed: 'উপহাৰ ৰিডিম কৰা হৈছে',
        Gift_pending: 'উপহাৰ বাকী আছে',
        Gift_Delivered: 'উপহাৰ ডেলিভাৰী কৰা হৈছে',
        Gift_Rejected:'উপহাৰ নাকচ কৰা হৈছে',
        Gift_Order_Placed:'উপহাৰৰ অৰ্ডাৰ স্থাপন কৰা হৈছে',
        Query_Raised: 'প্ৰশ্ন উত্থাপন কৰা হৈছে',
        Query_pending: 'প্ৰশ্ন বাকী আছে',
        Query_resolved: 'প্ৰশ্নৰ সমাধান হ’ল',
        Dealer: 'ডিলাৰ',
        Mason_mobile: 'ঠিকাদাৰ মোবাইল',
        Mason_branch: 'ঠিকাদাৰ শাখা',
        Te_Code: "বিডিই ক'ড",
        Te_Name: 'বিডিই নাম',
        Te_Phone: 'বিডিই ফোন',
        Zone: "জ'ন",
        Product_name: 'প্ৰডাক্টৰ নাম',
        Product_quantity: 'পণ্যৰ পৰিমাণ',
        Verified_by: 'দ্বাৰা পৰীক্ষা কৰা হৈছে',
        Adhaar: 'আধাৰ',
        DOB: 'জন্ম তাৰিখ',
        Marrital_Status: 'বৈবাহিক অৱস্থা',
        Spouce_Name: 'পত্নীৰ নাম',
        Spouce_DOB: 'পত্নী জন্ম তাৰিখ',
        Branch_Name: 'শাখাৰ নাম',
        Zone_Name: "জ'নৰ নাম",
        Created_By: 'দ্বাৰা সৃষ্টি কৰা হৈছে',
        Linked_TE_Name: 'লিংক কৰা বিডিই নাম',
        Mason_category: 'ঠিকাদাৰ শ্ৰেণী',
        Order_no: 'অৰ্ডাৰ নং',
        Employee_name: 'কৰ্মচাৰীৰ নাম',
        Catalogue: 'কেটেলগ',
        Type: 'প্ৰকাৰ',
        Updated_at: 'আপডেট কৰা হৈছে',
        DASHBOARD_DETAILS: 'ডেচবৰ্ডৰ বিৱৰণ',
        PHONE_NO: 'ফোন নম্বৰ।',
        Select_Dealer_Rssd_Sub_Dealer: 'ডিলাৰ/আৰএছএছঘ/উপ-ডিলাৰ নিৰ্বাচন কৰক',
        Select_Dealer: 'ডিলাৰ নিৰ্বাচন কৰক',
        ENTER_OTP: 'অ’টিপি প্ৰৱেশ কৰক',
        Verify_from_OTP: 'অ’টিপি পৰীক্ষা কৰক',
        Verify_from_Star_Saathi: 'ষ্টাৰ মেটৰ পৰা পৰীক্ষা কৰক',
        DELIVERY_ADDRESS: 'ডেলিভাৰীৰ ঠিকনা',
        Change_delivery_address: 'ডেলিভাৰীৰ ঠিকনা সলনি কৰক',
        Confirm: 'নিশ্চিত',
        Select_options: 'বিকল্পসমূহ নিৰ্ব্বাচন কৰক',
        Camera: 'কেমেৰাটো',
        Library: 'ফাইল',
        Close: 'বন্ধ',
        No_Internet_connection: 'ইণ্টাৰনেট সংযোগ নাই',
        Select_Language: 'ভাষা নিৰ্বাচন কৰক',
        start_date:'আৰম্ভণিৰ তাৰিখ',
        end_date:'শেষৰ তাৰিখ',
        Phone_no_is_required:'ফোন নংৰ প্ৰয়োজন',
        Verified:'পৰীক্ষা কৰা হৈছে',
        Send_OTP:'অ’টিপি পঠাওক',
        Select_Language:'ভাষা নিৰ্বাচন কৰক',
        Loading:'লোড হৈ আছে'
      }
    case 'Bengali':
      return {
        Search_by_mobile_number:'মোবাইল নম্বর দিয়ে অনুসন্ধান করুন',
        Contractor_Profile:'ঠিকাদার প্রোফাইল',
        Email:'ই-মেইল',
        Updated_Profile:'আপডেট করা প্রোফাইল',
        Updated:'আপডেট করা হয়েছে',
        Action_Need:'অ্যাকশন প্রয়োজন',
        Contractor_List:'ঠিকাদার তালিকা',
        sorry:'দুঃখিত',
        Date_of_Lifting:'উত্তোলনের তারিখ',
        Linked_Dealer:'লিঙ্কড ডিলার',
        ADD_ENQUIRY:'তদন্ত যোগ করুন',
        transaction_id:'লেনদেন আইডি',
        Sign_Up_To_Your_Mason:'আপনার ঠিকাদার\nসাইন আপ করুন',
        For_All_Your_Cement_Purchases:'আপনার সমস্ত সিমেন্ট ক্রয়ের জন্য',
        Check_Balance_Points:'ব্যালেন্স পয়েন্ট চেক করুন',
        Follow_Us:'আমাদের অনুসরণ করুন',
        otp_message_1:'আমরা ',
        otp_message_2:' ফোন নম্বরে যে কোডটি পাঠাই দয়া করে সেটি লিখুন',
        Verify_Code:'যাচাই কোড',
        HOME: 'অবতরণ পৃষ্ঠা',
        Home: 'অবতরণ পৃষ্ঠা',
        Delete: 'মুছে দিন',
        YES: 'হ্যাঁ',
        PROFILE: 'প্রোফাইল',
        Profile: 'প্রোফাইল',
        ORDER_LIST: 'আদেশ তালিকা',
        Order_List: 'আদেশ তালিকা',
        ABOUT_US: 'আমাদের সম্পর্কে',
        About_Us: 'আমাদের সম্পর্কে',
        CONTACT_US: 'আমাদের সাথে যোগাযোগ করুন',
        Contact_Us: 'আমাদের সাথে যোগাযোগ করুন',
        TERMS_CONDITIONS: 'নিয়ম ও শর্তাবলী',
        Terms_Conditions: 'নিয়ম ও শর্তাবলী',
        PRIVACY_POLICY: 'গোপনীয়তা নীতি',
        Privacy_Policy: 'গোপনীয়তা নীতি',
        Logout: 'লগআউট',
        Version: 'সংস্করণ',
        Delete_Account: 'অ্যাকাউন্ট মুছুন',
        MASON_REGISTRATION: 'ঠিকাদার\nরেজিস্ট্রেশন',
        LIFTING_HISTORY1: 'উত্তোলন\nইতিহাস',
        LIFTING_HISTORY: 'উত্তোলন ইতিহাস',
        REWARD_POINTS: 'পুরস্কার\nপয়েন্ট',
        DASHBOARD1: 'ড্যাশবোর্ড',
        DASHBOARD: 'ড্যাশবোর্ড',
        ADD_LIFTING1: 'উত্তোলন\nযোগ করুন',
        ADD_LIFTING: 'উত্তোলন যোগ করুন',
        GIFT_CATALOGUE1: 'উপহার\nক্যাটালগ',
        GIFT_CATALOGUE: 'উপহার ক্যাটালগ',
        REQUEST_A_DEALER: 'একজন ডিলারকে অনুরোধ করুন',
        REQUEST_A_DEALER1: 'একজন ডিলারকে\nঅনুরোধ করুন',
        MASON_SALES_ENTRY1: 'ঠিকাদার\nসেলস এন্ট্রি',
        MASON_SALES_ENTRY: 'ঠিকাদার সেলস এন্ট্রি',
        LIFTING_APPROVAL1: 'উত্তোলন\nঅনুমোদন',
        LIFTING_APPROVAL: 'উত্তোলন অনুমোদন',
        DEALER_LINK_REQUEST1: 'ডিলার লিঙ্ক\nঅনুরোধ',
        DEALER_LINK_REQUEST: 'ডিলার লিঙ্ক অনুরোধ',
        ORDER_ENQUIRY:'অর্ডার তদন্ত',
        ORDER_ENQUIRY1:'অর্ডার\nতদন্ত',
        NEW_ORDER_ENQUIRY:'নতুন আদেশ তদন্ত',
        Cancel: 'বাতিল করুন',
        Edit_Profile: 'প্রোফাইল সম্পাদনা করুন',
        Save: 'সংরক্ষণ করুন',
        Your_Name: 'আপনার নাম',
        Your_Phone_no: 'আপনার ফোন নম্বর',
        Your_Mail: 'আপনার মেইল',
        Technical_Engineer_Name: 'বিডিই নাম',
        Technical_Engineer_Mobile: 'বিডিই মোবাইল',
        Aadhaar_no: 'আধার নং',
        Categoty: 'শ্রেণী',
        Address_1: 'ঠিকানা ১',
        Address_2: 'ঠিকানা ২',
        City: 'শহর',
        District: 'জেলা',
        State: 'রাজ্য',
        Country: 'দেশ',
        Pin: 'জিপ কোড',
        Employee_Id: 'কর্মচারী আইডি',
        Employee_Id1: 'কর্মচারী আইডি',
        Aadhaar__documant:'আধার নথি',
        Dealer_Code: 'ডিলার কোড',
        Rssd_Code: 'আরএসএসডি কোড',
        Enter_your_Mobile_number: 'আপনার মোবাইল নম্বর লিখুন',
        Enter_mobile_number: 'মোবাইল নম্বর লিখুন',
        Next: 'পরবর্তী',
        Dont_have_an_account_yet: 'এখনও একটি অ্যাকাউন্ট নেই?',
        for_Mason: 'ঠিকাদার জন্য',
        Or: 'বা',
        for_Technical_Engineer: 'বিডিই জন্য',
        Verification_code: 'যাচাইকরণ কোড',
        Enter_code: 'কোড লিখুন',
        Please_enter_verification_code: 'যাচাইকরণ কোড লিখুন',
        Send_to_your_mobile_no: 'আপনার মোবাইল নম্বরে পাঠান',
        Didnt_receive_an_OTP: 'একটি ওটিপি পাননি?',
        Resend_OTP: 'ওটিপি আবার পাঠান?',
        Verify: 'যাচাই করুন',
        MASON: 'ঠিকাদার',
        REGISTRATION: 'নিবন্ধন',
        Full_name_of_mason: 'পুরো নাম',
        Enter_Mobile_Number: 'মোবাইল নম্বর লিখুন',
        Enter_Email_Id:'ই-মেইল আইডি লিখুন',
        Search: 'অনুসন্ধান করুন',
        Marital_Status: 'বৈবাহিক অবস্থা',
        Select_branch: 'শাখা নির্বাচন করুন',
        Select_Technical_Engineer: 'বিডিই নির্বাচন করুন',
        DATE_OF_BIRTH: 'জন্ম তারিখ',
        Enter_Aadhar_number: 'আধার নম্বর লিখুন',
        Enter_Voter_number:'ভোটার নম্বৰ লিখক',
        Choose_File: 'ফাইল নির্বাচন করুন',
        Upload_Aadhaar: 'আধার আপলোড করুন',
        Upload_Voter: 'ভোটার আপলোড করুন',
        Register: 'নিবন্ধন করুন',
        TECHNICAL_ENGINEER: 'বিডিই',
        Full_name: 'পুরো নাম',
        Employee_Code: 'কর্মচারী কোড',
        Phone: 'ফোন',
        Your_number_is_verified: 'আপনার নম্বর যাচাই করা হয়েছে',
        Language_change_successfully:'ভাষা পরিবর্তন সফলভাবে',
        Successfully_language_changed: 'সফলভাবে ভাষা পরিবর্তন হয়েছে',
        Login: 'লগইন করুন',
        SUPPORT: 'সমর্থন',
        Get_In_Touch: 'যোগাযোগ করুন',
        Message: 'বাৰ্তা',
        Submit: 'জমা দিন',
        Submit1: 'জমা দিন',
        SUPPORT_LIST: 'সমর্থন তালিকা',
        Name: 'নাম',
        Comment: 'মন্তব্য',
        Status: 'স্থিতি',
        Pending: 'মুলতুবি',
        Resolved: 'সমাধান করা হয়েছে',
        Rejected: 'প্রত্যাখ্যাত',
        No_Data_Found: 'কোন তথ্য পাওয়া যায়নি',
        Gift_not_available: 'অনুগ্রহ করে পুরষ্কারের জন্য পরবর্তী স্ল্যাবে যোগ্যতা অর্জন করুন',
        REJECT: 'প্ৰত্যাখ্যান',
        ACCEPT: 'স্বীকার করুন',
        Approved: 'অনুমোদিত',
        Are_you_want_to_accept_the_lifting: 'আপনি কি লিফট\nগ্রহণ করতে চান?',
        Select_your_reason: 'আপনার কারণ নির্বাচন করুন',
        DATE: 'তারিখ',
        DESCRIPTION: 'বর্ণনা',
        POINTS: 'পয়েন্ট',
        EARNED: 'অর্জিত',
        REDEEMED: 'খালাস',
        REWARD_DETAILS: 'পুরস্কার বিবরণ',
        NET_POINTS: 'নেট পয়েন্ট',
        AVAILABLE_POINTS: 'উপলব্ধ পইণ্ট',
        Month: 'মাস',
        Year: 'বছর',
        Select_Mason: 'ঠিকাদার নির্বাচন করুন',
        Redeem_Now: 'এখনই রিডিম করুন',
        LINK: 'লিঙ্ক',
        Registration: 'নিবন্ধন',
        Successful: 'সফল',
        Order_Id: 'অর্ডার আইডি',
        Date: 'তারিখ',
        Description: 'বর্ণনা',
        Points: 'পয়েন্ট',
        Delivery_Status: 'ডেলিভারি স্ট্যাটাস',
        Delivered: 'বিতরণ করা হয়েছে',
        Delivery_Date: 'ডেলিভারি তারিখ',
        Support: 'সমর্থন',
        View_Support: 'সমর্থন দেখুন',
        NOTIFICATION: 'বিজ্ঞপ্তি',
        Enter_Code: 'কোড লিখুন',
        Please_Enter_Verification_Code: 'অনুগ্রহ করে যাচাইকরণ কোড লিখুন',
        Send_To_Your_Mobile: 'আপনার মোবাইলে পাঠান',
        Spouse_name: 'পত্নীর নাম',
        Spouse_DoB: 'স্ত্রীর জন্ম তারিখ',
        SPOUSES_DATE_OF_BIRTH: 'স্ত্রীর জন্ম তারিখ',
        EDIT: 'সম্পাদনা করুন',
        From_Date: 'তারিখ থেকে',
        To_Date: 'তারিখ থেকে',
        Are_you_want_to_accept_the_lifting: 'আপনি উত্তোলন\nগ্রহণ করতে চান?',
        Edit_Pending_Lifting: 'মুলতুবি উত্তোলন সম্পাদনা করুন',
        Product: 'সামগ্ৰী',
        Lifting_Date: 'উত্তোলনের তারিখ',
        Mason_Name: 'ঠিকাদার নাম',
        Mason_Phone: 'ঠিকাদার ফোন',
        No_of_Bags: 'ব্যাগের সংখ্যা',
        Accept: 'গ্রহণ করুন',
        PRODUCTS: 'পণ্য',
        NO_OF_BAGS: 'ব্যাগের সংখ্যা',
        LIFTING_DATE: 'উত্তোলনের তারিখ',
        POINTS: 'পয়েন্ট',
        In_progress: 'চলছে',
        DEALER: 'ডিলার',
        RSSD: 'আরএসএসডি',
        SUB_DEALER: 'সাব-ডিলার',
        STAR_SAATHI_STATUS: 'তারকা অংশীদার অবস্থা',
        APPROVED_REJECTED_DATE_AND_TIME: 'অনুমোদিত/প্রত্যাখ্যাত তারিখ এবং সময়',
        Search_Name: 'অনুসন্ধান নাম',
        Mobile_No: 'মোবাইল নম্বর',
        Aadhar: 'আধার',
        UPDATE_LIFTING_DETAILS: 'উত্তোলনের বিবরণ আপডেট করুন',
        Select_Product: 'পণ্য নির্বাচন করুন',
        Enter_Qty_No_Of_Bags: 'পরিমাণ লিখুন (ব্যাগের সংখ্যা)',
        Remarks: 'মন্তব্য',
        CANCEL: 'বাতিল করুন',
        UPDATE: 'আপডেট করুন',
        GIFT_REDEMPTION: 'উপহার রিডেম্পশন',
        Address: 'ঠিকানা',
        t0: 'iOS ইনপুট সাজেশনের জন্য রিঅ্যাক্ট নেটিভ 0.58+ প্রয়োজন এবং iOS 12 এবং তার উপরে কাজ করে। iOS ইনপুট সাজেশনের জন্য রিঅ্যাক্ট নেটিভ 0.58+ প্রয়োজন এবং iOS 12 এবং তার উপরে কাজ করে।',
        Total_Bags: 'মোট ব্যাগ',
        Are_you_sure_to_redeemed_this_product: 'আপনি কি এই পণ্যটি রিডিম করার বিষয়ে নিশ্চিত?',
        Redeem: 'খালাস',
        FAQ: 'প্রায়শই জিজ্ঞাসিত প্রশ্নাবলী',
        Total_Linked_Mason: 'মোট লিঙ্কড ঠিকাদার',
        Active_Mason: 'সক্রিয় ঠিকাদার',
        Verified_Lifting: 'যাচাইকৃত উত্তোলন',
        Unverified_Lifting: 'অযাচাইকৃত ওজন উত্তোলন',
        Total_Ppc_Lifting_Bag: 'মোট পিপিসি লিফটিং ব্যাগ',
        Total_Arc_Lifting_Bag: 'মোট আর্ক লিফটিং ব্যাগ',
        Mason_Net_Point: 'ঠিকাদার নেট পয়েন্ট',
        Gift_Redeemed: 'উপহার খালাস',
        Gift_pending: 'উপহার মুলতুবি',
        Gift_Delivered: 'উপহার বিতরণ করা হয়েছে',
        Gift_Rejected:'উপহার প্রত্যাখ্যাত',
        Gift_Order_Placed:'উপহারের অর্ডার দেওয়া হয়েছে',
        Query_Raised: 'প্রশ্ন উত্থাপিত',
        Query_pending: 'প্রশ্ন মুলতুবি',
        Query_resolved: 'প্রশ্ন সমাধান করা হয়েছে',
        Dealer: 'ডিলার',
        Mason_mobile: 'ঠিকাদার মোবাইল',
        Mason_branch: 'ঠিকাদার শাখা',
        Te_Code: 'বিডিই কোড',
        Te_Name: 'বিডিই নাম',
        Te_Phone: 'বিডিই ফোন',
        Zone: 'জোন',
        Product_name: 'পণ্যের নাম',
        Product_quantity: 'পণ্যের পরিমাণ',
        Verified_by: 'দ্বারা যাচাই করা হয়েছে',
        Adhaar: 'আধার',
        DOB: 'জন্ম তারিখ',
        Marrital_Status: 'বৈবাহিক অবস্থা',
        Spouce_Name: 'পত্নীর নাম',
        Spouce_DOB: 'স্ত্রীর জন্ম তারিখ',
        Branch_Name: 'শাখার নাম',
        Zone_Name: 'জোনের নাম',
        Created_By: 'দ্বারা নির্মিত',
        Linked_TE_Name: 'লিঙ্কড বিডিই নাম',
        Mason_category: 'ঠিকাদার বিভাগ',
        Order_no: 'অর্ডার নং',
        Employee_name: 'কর্মচারীর নাম',
        Catalogue: 'ক্যাটালগ',
        Type: 'টাইপ',
        Updated_at: 'এ আপডেট করা হয়েছে',
        DASHBOARD_DETAILS: 'ড্যাশবোর্ডের বিবরণ',
        PHONE_NO: 'ফোন নং',
        Select_Dealer_Rssd_Sub_Dealer: 'ডিলার/আরএসএসডি/সাব-ডিলার নির্বাচন করুন',
        Select_Dealer: 'ডিলার নির্বাচন করুন',
        ENTER_OTP: 'ওটিপি লিখুন',
        Verify_from_OTP: 'ওটিপি থেকে যাচাই করুন',
        Verify_from_Star_Saathi: 'স্টার সাথী থেকে যাচাই করুন',
        DELIVERY_ADDRESS: 'ডেলিভারি ঠিকানা',
        Change_delivery_address: 'বিতরণ ঠিকানা পরিবর্তন করুন',
        Confirm: 'নিশ্চিত করুন',
        Select_options: 'বিকল্প নির্বাচন করুন',
        Camera: 'ক্যামেরা',
        Library: 'ফাইল',
        Close: 'বন্ধ',
        No_Internet_connection: 'ইন্টারনেট সংযোগ নেই',
        Select_Language: 'ভাষা নির্বাচন করুন',
        start_date:'শুরুর তারিখ',
        end_date:'শেষ তারিখ',
        Phone_no_is_required:'ফোন নম্বর প্রয়োজন',
        Verified:'যাচাই করা হয়েছে',
        Send_OTP:'ওটিপি পাঠান',
        Select_Language:'ভাষা নির্বাচন করুন',
        Loading:'লোড হচ্ছে'
      }
    default:
      return {
        Search_by_mobile_number:'Search by mobile number',
        Contractor_Profile:'Contractor Profile',
        Email:'E-mail',
        Updated_Profile:'Updated Profile',
        Updated:'Updated',
        Action_Need:'Action Need',
        Contractor_List:'Contractor List',
        sorry:'Sorry',
        Date_of_Lifting:'Date of Lifting',
        Linked_Dealer:'Linked Dealer',
        ADD_ENQUIRY:'ADD ENQUIRY',
        transaction_id:"Transaction i'd",
        Sign_Up_To_Your_Mason:'Sign Up To\nYour Contractor',
        For_All_Your_Cement_Purchases:'For All Your Cement Purchases',
        Check_Balance_Points:'Check Balance Points',
        Follow_Us:'Follow Us',
        otp_message_1:'Please enter the code we just send to phone number',
        otp_message_2:'',
        Verify_Code:'Verify Code',
        HOME: 'HOME',
        Home: 'Home',
        Delete: 'Delete',
        YES: 'YES',
        PROFILE: 'PROFILE',
        Profile: 'Profile',
        ORDER_LIST: 'ORDER LIST',
        Order_List: 'Order List',
        ABOUT_US: 'ABOUT US',
        About_Us: 'About Us',
        CONTACT_US: 'CONTACT US',
        Contact_Us: 'Contact Us',
        TERMS_CONDITIONS: 'TERMS & CONDITIONS',
        Terms_Conditions: 'Terms & Conditions',
        PRIVACY_POLICY: 'PRIVACY POLICY',
        Privacy_Policy: 'Privacy Policy',
        Logout: 'Logout',
        Version: 'Version',
        Delete_Account: 'Delete Account',
        MASON_REGISTRATION: 'Contractor\nRegistration',
        LIFTING_HISTORY1: 'Lifting\nHistory',
        LIFTING_HISTORY: 'LIFTING HISTORY',
        REWARD_POINTS: 'Reward\nPoints',
        DASHBOARD1: 'Dashboard',
        DASHBOARD: 'DASHBOARD',
        ADD_LIFTING1: 'Add\nLifting',
        ADD_LIFTING: 'ADD LIFTING',
        GIFT_CATALOGUE1: 'Gift\nCatalogue',
        GIFT_CATALOGUE: 'GIFT CATALOGUE',
        REQUEST_A_DEALER: 'REQUEST A DEALER',
        REQUEST_A_DEALER1: 'Request\nA Dealer',
        MASON_SALES_ENTRY1: 'Contractor\nSales Entry',
        MASON_SALES_ENTRY: 'CONTRACTOR SALES ENTRY',
        LIFTING_APPROVAL1: 'Lifting\nApproval',
        LIFTING_APPROVAL: 'LIFTING APPROVAL',
        DEALER_LINK_REQUEST1: 'Dealer Link\nRequest',
        DEALER_LINK_REQUEST: 'DEALER LINK REQUEST',
        ORDER_ENQUIRY:'ORDER ENQUIRY',
        ORDER_ENQUIRY1:'Order\nEnquiry',
        NEW_ORDER_ENQUIRY:'NEW ORDER ENQUIRY',
        Cancel: 'Cancel',
        Edit_Profile: 'Edit Profile',
        Save: 'Save',
        Your_Name: 'Your Name',
        Your_Phone_no: 'Your Phone no',
        Your_Mail: 'Your Email',
        Technical_Engineer_Name: 'BDE Name',
        Technical_Engineer_Mobile: 'BDE Mobile',
        Aadhaar_no: 'Aadhaar no',
        Categoty: 'Categoty',
        Address_1: 'Address 1',
        Address_2: 'Address 2',
        City: 'City',
        District: 'District',
        State: 'State',
        Country: 'Country',
        Pin: 'Pin',
        Employee_Id: 'Employee Id',
        Employee_Id1: 'Employee ID',
        Aadhaar__documant:'Aadhaar Documant',
        Dealer_Code: 'Dealer Code',
        Rssd_Code: 'Rssd Code',
        Enter_your_Mobile_number: 'Enter your Mobile number',
        Enter_mobile_number: 'Enter mobile number',
        Next: 'Next',
        Dont_have_an_account_yet: "Don't have an account yet?",
        for_Mason: 'for Contractor',
        Or: 'Or',
        for_Technical_Engineer: 'for BDE',
        Verification_code: 'Verification code',
        Enter_code: 'Enter code',
        Please_enter_verification_code: 'Please enter verification code',
        Send_to_your_mobile_no: 'Send to your mobile no',
        Didnt_receive_an_OTP: "Didn't receive an OTP?",
        Resend_OTP: 'Resend OTP?',
        Verify: 'Verify',
        MASON: 'CONTRACTOR',
        REGISTRATION: 'REGISTRATION',
        Full_name_of_mason: 'Full name of contractor',
        Enter_Mobile_Number: 'Enter Mobile Number',
        Enter_Email_Id:'Enter E-mail Id',
        Search: 'Search',
        Marital_Status: 'Marital Status',
        Select_branch: 'Select branch',
        Select_Technical_Engineer: 'Select BDE',
        DATE_OF_BIRTH: 'DATE OF BIRTH',
        Enter_Aadhar_number: 'Enter Aadhar number',
        Enter_Voter_number:'Enter Voter number',
        Choose_File: 'Choose File',
        Upload_Aadhaar: 'Upload Aadhaar',
        Upload_Voter: 'Upload Voter',
        Register: 'Register',
        TECHNICAL_ENGINEER: 'BDE',
        Full_name: 'Full name',
        Employee_Code: 'Employee Code',
        Phone: 'Phone',
        Your_number_is_verified: 'Your number is verified',
        Language_change_successfully:'Language change successfully',
        Successfully_language_changed: 'Successfully language changed',
        Login: 'Login',
        SUPPORT: 'SUPPORT',
        Get_In_Touch: 'Get In Touch',
        Message: 'Message',
        Submit: 'Submit',
        Submit1: 'SUBMIT',
        SUPPORT_LIST: 'SUPPORT LIST',
        Name: 'Name',
        Comment: 'Comment',
        Status: 'Status',
        Pending: 'Pending',
        Resolved: 'Resolved',
        Rejected: 'Rejected',
        No_Data_Found: 'No Data Found',
        Gift_not_available: 'No gift found.\nPlease qualify to the next slab for rewards',
        REJECT: 'REJECT',
        ACCEPT: 'ACCEPT',
        Approved: 'Approved',
        Are_you_want_to_accept_the_lifting: 'Are you want to\naccept the lifting?',
        Select_your_reason: 'Select your reason',
        DATE: 'DATE',
        DESCRIPTION: 'DESCRIPTION',
        POINTS: 'POINTS',
        EARNED: 'EARNED',
        REDEEMED: 'REDEEMED',
        REWARD_DETAILS: 'REWARD DETAILS',
        NET_POINTS: 'NET POINTS',
        AVAILABLE_POINTS: 'AVAILABLE POINTS',
        Month: 'Month',
        Year: 'Year',
        Select_Mason: 'Select Contractor',
        Redeem_Now: 'Redeem Now',
        LINK: 'LINK',
        Registration: 'Registration',
        Successful: 'Successful',
        Order_Id: 'Order Id',
        Date: 'Date',
        Description: 'Description',
        Points: 'Points',
        Delivery_Status: 'Delivery Status',
        Delivered: 'Delivered',
        Delivery_Date: 'Delivery Date',
        Support: 'Support',
        View_Support: 'View Support',
        NOTIFICATION: 'NOTIFICATION',
        Enter_Code: 'Enter Code',
        Please_Enter_Verification_Code: 'Please Enter Verification Code',
        Send_To_Your_Mobile: 'Send To Your Mobile',
        Spouse_name: 'Spouse name',
        Spouse_DoB: 'Spouse DOB',
        SPOUSES_DATE_OF_BIRTH: "SPOUSE'S DATE OF BIRTH",
        EDIT: 'EDIT',
        From_Date: 'From Date',
        To_Date: 'To Date',
        Are_you_want_to_accept_the_lifting: 'Are you want to\naccept the lifting?',
        Edit_Pending_Lifting: 'Edit Pending Lifting',
        Product: 'Product',
        Lifting_Date: 'Lifting Date',
        Mason_Name: 'Contractor Name',
        Mason_Phone: 'Contractor Phone',
        No_of_Bags: 'No of Bags',
        Accept: 'Accept',
        PRODUCTS: 'PRODUCTS',
        NO_OF_BAGS: 'NO OF BAGS',
        LIFTING_DATE: 'LIFTING DATE',
        POINTS: 'POINTS',
        In_progress: 'In-progress',
        DEALER: 'DEALER',
        RSSD: 'RSSD',
        SUB_DEALER: 'SUB-DEALER',
        STAR_SAATHI_STATUS: 'STAR SAATHI STATUS',
        APPROVED_REJECTED_DATE_AND_TIME: 'APPROVED/REJECTED DATE AND TIME',
        Search_Name: 'Search Name',
        Mobile_No: 'Mobile No',
        Aadhar: 'Aadhar',
        UPDATE_LIFTING_DETAILS: 'UPDATE LIFTING DETAILS',
        Select_Product: 'Select Product',
        Enter_Qty_No_Of_Bags: 'Enter Qty(No Of Bags)',
        Remarks: 'Remarks',
        CANCEL: 'CANCEL',
        UPDATE: 'UPDATE',
        GIFT_REDEMPTION: 'GIFT REDEMPTION',
        Address: 'Address',
        t0: 'The iOS input suggestion requires React Native 0.58+ and works for iOS 12 and above. The iOS input suggestion requires React Native 0.58+ and works for iOS 12 and above.',
        Total_Bags: 'Total Bags',
        Are_you_sure_to_redeemed_this_product: 'Are you sure to redeemed this product?',
        Redeem: 'Redeem',
        FAQ: 'FAQ',
        Total_Linked_Mason: 'Total Linked Contractor',
        Active_Mason: 'Active Contractor',
        Verified_Lifting: 'Verified Lifting',
        Unverified_Lifting: 'Unverified Lifting',
        Total_Ppc_Lifting_Bag: 'Total Ppc Lifting Bag',
        Total_Arc_Lifting_Bag: 'Total Arc Lifting Bag',
        Mason_Net_Point: 'Contractor Net Point',
        Gift_Redeemed: 'Gift Redeemed',
        Gift_pending: 'Gift pending',
        Gift_Delivered: 'Gift Delivered',
        Gift_Rejected:'Gift Rejected',
        Gift_Order_Placed:'Gift Order Placed',
        Query_Raised: 'Query Raised',
        Query_pending: 'Query pending',
        Query_resolved: 'Query resolved',
        Dealer: 'Dealer',
        Mason_mobile: 'Contractor mobile',
        Mason_branch: 'Contractor branch',
        Te_Code: 'BDE Code',
        Te_Name: 'BDE Name',
        Te_Phone: 'BDE Phone',
        Zone: 'Zone',
        Product_name: 'Product name',
        Product_quantity: 'Product quantity',
        Verified_by: 'Verified by',
        Adhaar: 'Adhaar',
        DOB: 'DOB',
        Marrital_Status: 'Marrital Status',
        Spouce_Name: 'Spouce Name',
        Spouce_DOB: 'Spouce DOB',
        Branch_Name: 'Branch Name',
        Zone_Name: 'Zone Name',
        Created_By: 'Created By',
        Linked_TE_Name: 'Linked BDE Name',
        Mason_category: 'Contractor category',
        Order_no: 'Order no',
        Employee_name: 'Employee name',
        Catalogue: 'Catalogue',
        Type: 'Type',
        Updated_at: 'Updated at',
        DASHBOARD_DETAILS: 'DASHBOARD DETAILS',
        PHONE_NO: 'PHONE NO.',
        Select_Dealer_Rssd_Sub_Dealer: 'Select Dealer/Rssd/Sub-Dealer',
        Select_Dealer: 'Select Dealer',
        ENTER_OTP: 'ENTER OTP',
        Verify_from_OTP: 'Verify from OTP',
        Verify_from_Star_Saathi: 'Verify from Star Saathi',
        DELIVERY_ADDRESS: 'DELIVERY ADDRESS',
        Change_delivery_address: 'Change delivery address',
        Confirm: 'Confirm',
        Select_options: 'Select options',
        Camera: 'Camera',
        Library: 'Library',
        Close: 'Close',
        No_Internet_connection: 'No Internet Connection',
        Select_Language: 'Select Language',
        start_date:'Start date',
        end_date:'End date',
        Phone_no_is_required:'Phone no is required',
        Verified:'Verified',
        Send_OTP:'Send OTP',
        Select_Language:'Select Language',
        Loading:'Loading'
      }
  }
}

export default useTextValue